#!/usr/bin/env python3
"""Build the Atari side of ACSI2TNFS: boot code, driver, the flash
disk image and disk_seed.h for the firmware.

The version comes from ../version.txt (written to version.inc for the 68000
sources). vasm: $VASM, else ~/.pico-sdk/vasm/vasm/vasmm68k_mot(.exe), else PATH.

Layout (512-byte sectors, must match acsi.h / layout.inc):
  LBA 0            Atari root sector: boot code, hd_siz, 1 GEM partition
  LBA 1..8         driver (DRV.BIN)
  LBA 16..end      GEM partition, FAT16, 2 sectors per cluster
"""
import os, shutil, struct, subprocess, sys, time

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
OUT = os.path.join(HERE, "out")

DISK_SECTORS = 2040            # acsi.h
DISK_FLASH_OFFSET = 0x100000   # acsi.h
DRVSECT = 8                    # layout.inc
PSTART = 16
ROOT_ENTRIES = 256
SPC = 2
FILES_DIR = os.path.join(HERE, "files")


def be16(b, off): return (b[off] << 8) | b[off + 1]


def version():
    with open(os.path.join(ROOT, "version.txt")) as f:
        return f.readline().strip()


def vasm():
    for c in (os.environ.get("VASM"),
              os.path.expanduser("~/.pico-sdk/vasm/vasm/vasmm68k_mot.exe"),
              os.path.expanduser("~/.pico-sdk/vasm/vasm/vasmm68k_mot"),
              shutil.which("vasmm68k_mot")):
        if c and os.path.exists(c):
            return c
    sys.exit("vasmm68k_mot not found (set VASM)")


def assemble(ver):
    """version.inc, then BOOT.BIN and DRV.BIN into out/"""
    inc = ("; generated by mkdisk.py from version.txt - do not edit\n"
           "VERSION macro\n"
           f"        dc.b    \"{ver}\"\n"
           "        endm\n")
    path = os.path.join(HERE, "version.inc")
    if not os.path.exists(path) or open(path).read() != inc:
        open(path, "w").write(inc)
    os.makedirs(OUT, exist_ok=True)
    asm = vasm()
    for src, fmt, out in (("boot.s", "bin", "BOOT.BIN"), ("driver.s", "bin", "DRV.BIN")):
        subprocess.run([asm, "-quiet", "-m68000", "-F" + fmt, "-nosym",
                        "-o", os.path.join(OUT, out), src], cwd=HERE, check=True)
    print(f"  assembled boot code and driver (version {ver})")


def root_sector(boot, psize):
    s = bytearray(512)
    assert len(boot) <= 0x1c2, "boot code too large"
    s[:len(boot)] = boot
    struct.pack_into(">I", s, 0x1c2, DISK_SECTORS)                      # hd_siz
    struct.pack_into(">B3sII", s, 0x1c6, 0x81, b"GEM", PSTART, psize)  # p0
    total = sum(be16(s, i) for i in range(0, 510, 2)) & 0xffff
    struct.pack_into(">H", s, 510, (0x1234 - total) & 0xffff)          # bootable
    return s


def dos_datetime(t):
    lt = time.localtime(t)
    d = ((lt.tm_year - 1980) << 9) | (lt.tm_mon << 5) | lt.tm_mday
    tm = (lt.tm_hour << 11) | (lt.tm_min << 5) | (lt.tm_sec // 2)
    return tm, d


def fat16_partition(psize, files):
    bps = 512
    rdlen = ROOT_ENTRIES * 32 // bps
    res = 1
    # FAT size: iterate until stable
    # FAT type follows the cluster count (< 4085 = FAT12), because EmuTOS and
    # DOS decide it that way; a small FAT16 volume is misread by them.
    spf = 1
    while True:
        ncl = (psize - res - 2 * spf - rdlen) // SPC
        fat12 = ncl < 4085
        fatbytes = ((ncl + 2) * 3 + 1) // 2 if fat12 else (ncl + 2) * 2
        need = (fatbytes + bps - 1) // bps
        if need <= spf:
            break
        spf = need
    datrec = res + 2 * spf + rdlen
    img = bytearray(psize * bps)

    bs = bytearray(512)
    bs[0:3] = b"\xeb\x3c\x90"
    bs[3:11] = b"ACSI2TNF"
    struct.pack_into("<HBHBHHBHHHII", bs, 11, bps, SPC, res, 2, ROOT_ENTRIES,
                     psize, 0xf8, spf, 32, 2, 0, 0)
    bs[0x26] = 0x29
    struct.pack_into("<I", bs, 0x27, 0x2026ac51)
    bs[0x2b:0x36] = b"ACSI2TNFS  "
    bs[0x36:0x3e] = b"FAT12   " if fat12 else b"FAT16   "
    bs[510:512] = b"\x55\xaa"
    img[0:512] = bs

    fat = [0] * (ncl + 2)
    fat[0], fat[1] = (0xff8, 0xfff) if fat12 else (0xfff8, 0xffff)
    rootdir = bytearray(rdlen * bps)
    tm, dt = dos_datetime(time.time())
    struct.pack_into("<11sB10xHHHI", rootdir, 0, b"ACSI2TNFS  ", 0x08, tm, dt, 0, 0)
    ent = 1
    nextcl = 2
    for name, data in files:
        base, ext = name.upper().split(".")
        n83 = base.ljust(8).encode() + ext.ljust(3).encode()
        ncls = max(1, (len(data) + SPC * bps - 1) // (SPC * bps)) if data else 0
        first = nextcl if data else 0
        for i in range(ncls):
            c = nextcl + i
            fat[c] = c + 1 if i < ncls - 1 else (0xfff if fat12 else 0xffff)
            off = (datrec + (c - 2) * SPC) * bps
            chunk = data[i * SPC * bps:(i + 1) * SPC * bps]
            img[off:off + len(chunk)] = chunk
        nextcl += ncls
        # system files: read-only (the firmware keeps them up to date, console R restores them)
        struct.pack_into("<11sB10xHHHI", rootdir, ent * 32, n83, 0x01, tm, dt, first, len(data))
        ent += 1
    if fat12:
        fat += [0] * (len(fat) & 1)
        fatb = bytearray()
        for i in range(0, len(fat), 2):
            v = fat[i] | (fat[i + 1] << 12)
            fatb += bytes((v & 0xff, (v >> 8) & 0xff, v >> 16))
    else:
        fatb = struct.pack("<%dH" % len(fat), *fat)
    for k in range(2):
        off = (res + k * spf) * bps
        img[off:off + len(fatb)] = fatb
    off = (res + 2 * spf) * bps
    img[off:off + len(rootdir)] = rootdir
    print(f"  FAT{12 if fat12 else 16}: {psize} sectors, spf={spf}, rdlen={rdlen}, datrec={datrec}, clusters={ncl}, used={nextcl - 2}")
    return img


def uf2(chunks):
    """chunks: list of (flash_address, bytes). Returns UF2 bytes."""
    blocks = []
    for addr, data in chunks:
        for i in range(0, len(data), 256):
            blocks.append((addr + i, data[i:i + 256].ljust(256, b"\0")))
    out = bytearray()
    for n, (addr, payload) in enumerate(blocks):
        hdr = struct.pack("<IIIIIIII", 0x0A324655, 0x9E5D5157, 0x2000, addr, 256,
                          n, len(blocks), 0xE48BFF56)
        out += hdr + payload + bytes(476 - 256) + struct.pack("<I", 0x0AB16F30)
    return out


def write_seed(disk):
    """disk_seed.h for the firmware: all 4 KB flash blocks up to the last
    non-empty sector. Blocks are stored as (block number, 4096 bytes); empty
    blocks in between are written as zeros by the firmware."""
    last = max(i for i in range(DISK_SECTORS) if any(disk[i * 512:(i + 1) * 512]))
    nblk = last // 8 + 1
    data = disk[:nblk * 4096]
    with open(os.path.join(ROOT, "disk_seed.h"), "w") as f:
        f.write("/* generated by atari/mkdisk.py - do not edit */\n#pragma once\n")
        f.write(f"#define DISK_SEED_BLOCKS {nblk}\n")
        f.write(f"static const unsigned char disk_seed[{len(data)}] = {{\n")
        for i in range(0, len(data), 32):
            f.write("  " + ",".join(str(b) for b in data[i:i + 32]) + ",\n")
        f.write("};\n")
    print(f"  seed: {nblk} blocks ({len(data)} bytes) -> disk_seed.h")


def main():
    assemble(version())
    boot = open(os.path.join(OUT, "BOOT.BIN"), "rb").read()
    drv = open(os.path.join(OUT, "DRV.BIN"), "rb").read()
    assert len(drv) <= DRVSECT * 512, "driver too large"
    files = [("README.TXT", open(os.path.join(FILES_DIR, "README.TXT"), "rb").read())]
    # GEM configuration program: SideTNFS-Config built with 'make acsi'
    prg = os.path.join(FILES_DIR, "ACSITNFS.PRG")
    if os.path.exists(prg):
        files.append(("ACSITNFS.PRG", open(prg, "rb").read()))
    # any other file in files/ goes on C: as well
    for name in sorted(os.listdir(FILES_DIR)):
        if name.upper() not in ("README.TXT", "ACSITNFS.PRG"):
            files.append((name.upper(), open(os.path.join(FILES_DIR, name), "rb").read()))

    psize = DISK_SECTORS - PSTART
    disk = bytearray(DISK_SECTORS * 512)
    disk[0:512] = root_sector(boot, psize)
    disk[512:512 + len(drv)] = drv
    disk[PSTART * 512:] = fat16_partition(psize, files)

    open(os.path.join(OUT, "disk.img"), "wb").write(disk)
    write_seed(disk)
    open(os.path.join(OUT, "disk.uf2"), "wb").write(uf2([(0x10000000 + DISK_FLASH_OFFSET, bytes(disk))]))
    fw = os.path.join(ROOT, "build", "acsi2tnfs.bin")
    if os.path.exists(fw):
        fwb = open(fw, "rb").read()
        assert len(fwb) < DISK_FLASH_OFFSET
        open(os.path.join(OUT, "full.uf2"), "wb").write(
            uf2([(0x10000000, fwb), (0x10000000 + DISK_FLASH_OFFSET, bytes(disk))]))
    print("  wrote", OUT)


if __name__ == "__main__":
    main()
